### ISSUE TITLE
Serializable AreaEffects

### ISSUE THREAD

**Issue by Sqeaky** [BlackToppStudios/Mezzanine#40]
Implement Serialize/DeSerialize methods for all AreaEffect classes.

**Comment by MakoEnergy** [comment]
This probably could be unit tested, but that raises some other issues.  Currently none of the other WorldObjects/WorldProxies currently have unit tests written for them.  Even if they did, the entire ECS(Entity/Component System) is still not what I would consider "stable" as an API.  There are ongoing refactors that will likely require re-writes of those tests.  

Getting the ECS stable and unit tested is it's own issue, and technically a part of this issue.  For that reason, and the fact that this issue will continue to just lurk otherwise without being all that productive, I am going to close it in favor of adding an issue related to the ECS.
