### ISSUE TITLE
Replace WorldTriggers with a more intelligent system

### ISSUE THREAD

**Issue by Sqeaky** [BlackToppStudios/Mezzanine#41]
Replace triggers with serializable script of some kind. This will have to have for #25 or something similar before it can be completed.

**Comment by MakoEnergy** [comment]
WorldTriggers aren't going to last through the Jagati refactor.  I believe this issue to be somewhat malformed as the title implies they'll continue to exist in some form.  Triggers may be replaced with scripts, or some "Gametype" construct.  So I will rename the issue rather than remove it in favor if making a new one.

**Comment by Sqeaky** [comment]
I agree, and scripting supercedes triggers.
